// Generated by CoffeeScript 1.7.1
(function() {
  exports.Heroine = (function() {
    function Heroine(value, numPlayers) {
      var _;
      this.value = value;
      this.dateScore = (function() {
        var _i, _results;
        _results = [];
        for (_ = _i = 1; 1 <= numPlayers ? _i <= numPlayers : _i >= numPlayers; _ = 1 <= numPlayers ? ++_i : --_i) {
          _results.push(0);
        }
        return _results;
      })();
      this.loveScore = (function() {
        var _i, _results;
        _results = [];
        for (_ = _i = 1; 1 <= numPlayers ? _i <= numPlayers : _i >= numPlayers; _ = 1 <= numPlayers ? ++_i : --_i) {
          _results.push(0);
        }
        return _results;
      })();
    }

    Heroine.prototype.date = function(playerIndex) {
      return this.dateScore[playerIndex] += 1;
    };

    Heroine.prototype.updateLoveScore = function() {
      var playerIndex, pureScore, score, totalDateScore, _i, _ref, _results;
      totalDateScore = ((function() {
        var _i, _len, _ref, _results;
        _ref = this.dateScore;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          score = _ref[_i];
          _results.push(score);
        }
        return _results;
      }).call(this)).reduce(function(x, y) {
        return x + y;
      });
      _results = [];
      for (playerIndex = _i = 0, _ref = this.loveScore.length - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; playerIndex = 0 <= _ref ? ++_i : --_i) {
        pureScore = this.value * this.dateScore[playerIndex];
        if (pureScore > 0) {
          _results.push(this.loveScore[playerIndex] += pureScore / totalDateScore);
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    };

    Heroine.prototype.getBestPlayers = function(players) {
      var bestPlayers, maxScore, player, _i, _len;
      maxScore = Math.max.apply(null, this.loveScore);
      bestPlayers = [];
      for (_i = 0, _len = players.length; _i < _len; _i++) {
        player = players[_i];
        if (this.loveScore[player.index] === maxScore) {
          bestPlayers.push(player);
        }
      }
      return bestPlayers;
    };

    return Heroine;

  })();

}).call(this);
