// Generated by CoffeeScript 1.7.1
(function() {
  var Game, game, moves, playerIndex, _, _i, _j, _ref, _ref1;

  Game = require('./Game.coffee').Game;

  game = new Game(4);

  game.populateHeroines(10);

  while (!game.isFinished()) {
    moves = [];
    for (playerIndex = _i = 0, _ref = game.numPlayers - 1; 0 <= _ref ? _i <= _ref : _i >= _ref; playerIndex = 0 <= _ref ? ++_i : --_i) {
      moves[playerIndex] = [];
      for (_ = _j = 0, _ref1 = game.turn; 0 <= _ref1 ? _j <= _ref1 : _j >= _ref1; _ = 0 <= _ref1 ? ++_j : --_j) {
        moves[playerIndex].push(Math.floor(Math.random() * game.heroines.length));
      }
    }
    game.proceed(moves);
  }

  console.log(game.getRanking());

}).call(this);
