// Generated by CoffeeScript 1.7.1
(function() {
  var Game, game, moves, playerIndex, _, _i, _j, _k, _ref, _ref1;

  Game = require('./Game').Game;

  game = new Game(4);

  for (_ = _i = 1; _i <= 10; _ = ++_i) {
    game.addHeroine(Math.floor(Math.random() * 6) + 1);
  }

  while (!game.isFinished()) {
    moves = [];
    for (playerIndex = _j = 0, _ref = game.numPlayers; 0 <= _ref ? _j <= _ref : _j >= _ref; playerIndex = 0 <= _ref ? ++_j : --_j) {
      moves[playerIndex] = [];
      for (_ = _k = 0, _ref1 = game.turn; 0 <= _ref1 ? _k <= _ref1 : _k >= _ref1; _ = 0 <= _ref1 ? ++_k : --_k) {
        moves[playerIndex].push(Math.floor(Math.random() * game.heroines.length));
      }
    }
    game.proceed(moves);
  }

  console.log(game.getRanking());

}).call(this);
