// Generated by CoffeeScript 1.7.1
(function() {
  var Player;

  Player = (function() {
    function Player(index) {
      this.index = index;
      this.star = 0;
      this.totalLoveScore = 0;
    }

    Player.compareTo = function(self, other) {
      if (self.star === other.star) {
        if (self.totalLoveScore > other.totalLoveScore) {
          return 1;
        } else if (self.totalLoveScore < other.totalLoveScore) {
          return -1;
        } else {
          return 0;
        }
      } else {
        if (self.star > other.star) {
          return 1;
        } else {
          return -1;
        }
      }
    };

    return Player;

  })();

  exports.Player = Player;

}).call(this);
